Controllers/CategorysController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CompShop2.Models;

namespace CompShop2.Controllers
{
    public class CategorysController : Controller
    {
        private CSEntities db = new CSEntities();
        [Authorize(Roles = "Seller,Manager")]
        public ActionResult Index()
        {
            return View(db.Categorys.ToList());
        }
        [Authorize(Roles = "Seller,Manager")]
        // GET: Categorys/Details/5
        public ActionResult Details(int id)
        {
            Categorys categorys = db.Categorys.Find(id);
            if (categorys == null)
            {
                return HttpNotFound();
            }
            return View(categorys);
        }

      
        // GET: Categorys/Create
        public ActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Manager")]
        // POST: Categorys/Create
        [HttpPost]
        public ActionResult Create(Categorys categorys)
        {
            if (ModelState.IsValid)
            {
                db.Categorys.Add(categorys);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(categorys);
        }

        [Authorize(Roles = "Manager")]
        // GET: Categorys/Edit/5
        public ActionResult Edit(int id=0)
        {
            Categorys categorys = db.Categorys.Find(id);
            if (categorys == null)
            {
                return HttpNotFound();
            }
            return View(categorys);
        }
        
        [HttpPost]
        public ActionResult Edit(Categorys categorys)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categorys).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(categorys);
        }

        [Authorize(Roles = "Manager")]
        // GET: Categorys/Delete/5
        public ActionResult Delete(int id = 0)
        {
            Categorys categorys = db.Categorys.Find(id);
            if (categorys == null)
            {
                return HttpNotFound();
            }
            return View(categorys);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            db.Categorys.Remove(db.Categorys.Find(id));
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Controllers/ProvidersController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CompShop2.Models;

namespace CompShop2.Controllers
{
    public class ProvidersController : Controller
    {
        private CSEntities db = new CSEntities();
        [Authorize(Roles = "Manager")]
        public ActionResult Index()
        {
            return View(db.Providers.ToList());
        }

        [Authorize(Roles = "Manager")]
        public ActionResult Details(int id = 0)
        {
            Providers providers= db.Providers.Find(id);
            if (providers == null)
            {
                return HttpNotFound();
            }
            return View(providers);
        }

       
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Manager")]
        [HttpPost]
        public ActionResult Create(Providers providers)
        {
            if (ModelState.IsValid)
            {
                db.Providers.Add(providers);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(providers);
        }

       [Authorize(Roles = "Manager")]
            public ActionResult Edit(int id = 0)
        {
            Providers providers = db.Providers.Find(id);
            if (providers == null)
            {
                return HttpNotFound();
            }
            return View(providers);
        }

        [HttpPost]
        public ActionResult Edit(Providers providers)
        {
            if (ModelState.IsValid)
            {
                db.Entry(providers).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(providers);
        }


        [Authorize(Roles = "Manager")]
        public ActionResult Delete(int id = 0)
        {
            Providers providers = db.Providers.Find(id);
            if (providers == null)
            {
                return HttpNotFound();
            }
            return View(providers);
        }

            [HttpPost, ActionName("Delete")]
            public ActionResult DeleteConfirmed(int id)
            {
                db.Providers.Remove(db.Providers.Find(id));
                db.SaveChanges();
                return RedirectToAction("Index");
           }
        
    }
}

Controllers/WorkersController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Security.Claims;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using CompShop2.Models;
using System.Data.Entity.Validation;

namespace CompShop2.Controllers
{
    public class WorkersController : Controller
    {
        private CSEntities db = new CSEntities();


        
        // GET: Workers
        public ActionResult Index()
        {
            var Cat = db.Workers.Include(p => p.Salary);
            return View(Cat.ToList());
        }
        
        // GET: Workers/Create
        public ActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Create(Workers workers)
        {
            if (ModelState.IsValid)
            {
                db.Workers.Add(workers);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(workers);
        }

       
        public ActionResult Account()
        {
            var identity = (ClaimsPrincipal)Thread.CurrentPrincipal;
            var email = HttpContext.User.Identity.Name;
            string c = email;

            Workers workers = db.Workers.Where(l => l.Name == c).First();
           
            return View(workers);
        }



        [Authorize(Roles = "Manager")]
        public ActionResult Prodaga(int ProdID,int days)
        {
            try
            {
                DateTime date = DateTime.Now.AddDays(-days);
                IEnumerable<Transaction> transaction = db.Transaction.Where(w => w.Seller == ProdID && w.Date > date).Include(w =>w.Goods).ToList();

                return View(transaction);
            }
            catch
            {
                return RedirectToAction("Index","Home");
            }
        }
        [Authorize(Roles = "Manager")]
        public ActionResult Extra(int id, double sum)
        {
           Salary salary = db.Salary.Where(l => l.SellerID == id).First() ;
       salary.Extras += sum;
            db.SaveChanges();
       salary.Finaly = (double)(salary.Base + salary.Extras);
       db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        // GET: Workers/Edit/5
        public ActionResult Edit(int id)
        {
            Workers workers = db.Workers.Find(id);
            if (workers == null)
            {
                return HttpNotFound();
            }
            return View(workers);
        }

        // POST: Workers/Edit/5
        [HttpPost]
        public ActionResult Edit(Workers workers)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(workers).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(workers);
            }
            catch (DbEntityValidationException e)
            {
                Session["error"] = e.EntityValidationErrors;
                return RedirectToAction("Index");
            }
        }

        // GET: Workers/Delete/5


        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Delete(int id = 0)
        {
            db.Workers.Remove(db.Workers.Find(id));
            db.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Компьютерный магазин</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Компьютерный магазин", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Товары", "Index", "Home")</li>
                    <li>@Html.ActionLink("Категории товаров", "Index", "Categorys")</li>

                    @{if (User.IsInRole("Manager"))
                        {<li>@Html.ActionLink("Поставщики", "Index", "Providers")</li> } }
                    @{if ((User.IsInRole("Manager")) || (User.IsInRole("Admin")))
                        {<li>@Html.ActionLink("Сотрудники", "Index", "Workers")</li>}
                        }
                            <li>@Html.ActionLink("Личный кабинет", "Account", "Workers")</li>
                        </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Курсовой проект</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @Scripts.Render("~/scripts/jquery-3.4.1.js")
    @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.js")
</body>
</html>